apiVersion: v1
kind: Service
metadata:
  name: spark-history-svc
  labels:
    name: spark-history-svc
spec:
  ports:
    - name: spark-history
      port: 8080
      targetPort: 8080
  type: NodePort
  selector:
    name: spark-master-robin

