apiVersion: v1
kind: ReplicationController
metadata:
  name: spark-worker-robin-rc
spec:
  replicas: 3
  selector:
    name: spark-worker-robin
  template:
    metadata:
      labels:
        name: spark-worker-robin
    spec:
      containers:
      - name: spark-worker-robin
        image: robinlin/spark-worker
        command:
         - /start.sh
        args: 
         - spark-master-svc
