apiVersion: v1
kind: ReplicationController
metadata:
  name: hadoop-datanode-rc
spec:
  replicas: 3
  selector:
    name: hadoop-datanode
  template:
    metadata:
      labels:
        name: hadoop-datanode
    spec:
      containers:
      - name: hadoop-datanode
        image: robinlin/hadoop-datanode
        command:
         - /start.sh
        args:
         - hadoop-datanode
