apiVersion: v1
kind: Service
metadata:
  name: hadoop-webhdfs
  labels:
    name: hadoop-webhdfs
spec:
  ports:
    - name: hadoop-webhdfs
      port: 50070
      targetPort: 50070
  type: NodePort
  selector:
    name: hadoop-namenode
