apiVersion: v1
kind: ReplicationController
metadata:
  name: hadoop-namenode-rc
spec:
  replicas: 1
  selector:
    name: hadoop-namenode
  template:
    metadata:
      labels:
        name: hadoop-namenode
    spec:
      containers:
      - name: hadoop-namenode
        image: robinlin/hadoop-namenode
        command:
         - /start.sh
        args:
         - hadoop-namenode
        ports:
         - name: hadoop-namenode
           containerPort: 8020
         - name: hadoop-webhdfs
           containerPort: 50070
