apiVersion: v1
kind: Service
metadata:
  name: hadoop-namenode
  labels:
    name: hadoop-namenode
spec:
  ports:
    - name: hadoop-namenode
      port: 8020
      targetPort: 8020
  selector:
    name: hadoop-namenode
