apiVersion: v1
kind: Service
metadata: 
  name: spark-master-svc
  labels: 
    name: spark-master-svc
spec: 
  ports:
    - name: spark-history
      port: 8080
      targetPort: 8080
    - name: spark-master
      port: 7077
      targetPort: 7077
  type: NodePort
  selector: 
    name: spark-master-robin
